### PR TITLE
Adds `options.ignoreTrailing` which defaults to `false`.

### LINKED ISSUE #13: Suppress last empty line
Hey,

I see https://github.com/dominictarr/split/commit/078cfb4213c43f106fc439fb4358f95bef3a8bf6 fixes someones wish to get the last empty line (or whatever concept they're using to split). That's the same behavior I personally _don't_ want as I'm using Split for converting a stream of delimited records to individual objects.

How would I suppress the last empty string from being emitted? Or is Split not the right stream module for that case?

Thanks!

PS. The comparison to `null` seems pointless given that `soFar` is initialized to an empty string at the top of the file ensuring it can never be anything other than a string.

### PR DESCRIPTION
**Pull request by jxson**
I think this might close #13

### CODE REVIEW

**Comment by dominictarr** [comment]
can it be `{trailing: false}` and default it to true? I just have a thing where I hate camel names when a horse name is sufficient.

**Comment by jxson** [comment]
Totally.

**Comment by raine** [comment]
ping @dominictarr

**Comment by dominictarr** [comment]
merged into 1.0.0

**Pull request merged**
